name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: devanshyadav0001
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-dark
            dist/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=orange&color_dots=#0d1117,#003d00,#006600,#009900,#00cc00
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}